config/routes.rb
TiaAmparo::Application.routes.draw do

  get "tinymce_assets/create"

################disenyo_restauracion###############################
  get "disenyo/create"
  match 'disenyo' => 'disenyo#new', :as => 'disenyo', :via => :get
  match 'disenyo' => 'disenyo#create', :as => 'disenyo', :via => :post
################disenyo_restauracion#################

############zona verde######################
  resources :comments
  get "blog/index"
  match 'blog' => 'blog#new', :as => 'blog', :via => :get
  match 'blog' => 'blog#create', :as => 'blog', :via => :post
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :articles do
    collection do
      put :busqueda
    end
    resources :comments
  end
############zona verde###########################

############preguntas_frecuentes###########################
  get "preguntas_frecuentes/index"  ,as: 'preguntas_frecuentes'
############preguntas_frecuentes###########################

#########admin#########################
  get 'admin' => 'admin#index'
  get 'limpiezaBD' => 'admin#limpiezaBD'
#########admin##########################

#########usuarios#########################
  resources :password_resets
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources  :users do
    collection do
      get :areaUsuario
      put :busqueda
    end
  end
##########usuarios########################

##########tienda########################
  resources :gastos_envios do
    collection do
      get :resetearValores
      get :gastosEnvioCero
    end
  end
  resources  :line_items,:carts
  match 'store' => 'store#index', :as => 'store', :via => :get
  get "/store/index"
  get "/store/ceramica"
  get "/store/pintura"
  get "/store/jabones_naturales"
  get "/store/serijos"
  get "/store/bisuteria"
  get "/store/decoracion"
  get "/store/antiguedades"
  get "/store/muebles"
  get "/store/vinos"
  get "/store/quesos"
  get "/store/souvenires"
  get "/store/varios"
  put "/store/busqueda"

  resources :products do
    collection do
      put :busqueda
    end
  end

  resources :orders do
    collection do
      put :busqueda
    end
  end
##########tienda########################

############galeria_fotos######################
  resources :galeria_fotos do
    collection do
      get :verGaleriaFotos
      put :busqueda
    end
  end
############galeria_fotos#####################

############contacto#####################
  get "contacto/create"
  match 'contacto' => 'contacto#new', :as => 'contacto', :via => :get
  match 'contacto' => 'contacto#create', :as => 'contacto', :via => :post
############contacto#####################

############inicio#####################
  get "inicio/index"
  root to: 'inicio#index' , as: 'inicio'
############inicio#####################
end

app/models/gastos_envio.rb
class GastosEnvio < ActiveRecord::Base
  attr_accessible :kilos, :precio, :tipo

  validates :kilos, :precio, :tipo, :presence => true
  validates_uniqueness_of :id
end

app/controllers/gastos_envios_controller.rb
# encoding: utf-8
class GastosEnviosController < ApplicationController
  skip_before_filter :authorize , only: []
  skip_before_filter :filtro_admin , only: []
  # GET /gastos_envios
  # GET /gastos_envios.json
  def index
    @gastos_envios = GastosEnvio.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gastos_envios }
    end
  end

  # GET /gastos_envios/1
  # GET /gastos_envios/1.json
  def show
    @gastos_envio = GastosEnvio.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gastos_envio }
    end
  end

  # GET /gastos_envios/new
  # GET /gastos_envios/new.json
  def new
    @gastos_envio = GastosEnvio.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gastos_envio }
    end
  end

  # GET /gastos_envios/1/edit
  def edit
    @gastos_envio = GastosEnvio.find(params[:id])
  end

  # POST /gastos_envios
  # POST /gastos_envios.json
  def create
    @gastos_envio = GastosEnvio.new(params[:gastos_envio])
    respond_to do |format|
      if @gastos_envio.save
        format.html { redirect_to gastos_envios_path, notice: 'Gastos envio fue creado con éxito.' }
        format.json { render json: @gastos_envio, status: :created, location: @gastos_envio }
      else
        format.html { render action: "new" }
        format.json { render json: @gastos_envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gastos_envios/1
  # PUT /gastos_envios/1.json
  def update
    @gastos_envio = GastosEnvio.find(params[:id])
    respond_to do |format|
      if @gastos_envio.update_attributes(params[:gastos_envio])
        format.html { redirect_to gastos_envios_path, notice: 'Gastos envio fue editado con éxito.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gastos_envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gastos_envios/1
  # DELETE /gastos_envios/1.json
  def destroy
    @gastos_envio = GastosEnvio.find(params[:id])
    @gastos_envio.destroy
    respond_to do |format|
      format.html { redirect_to gastos_envios_url }
      format.json { head :no_content }
    end
  end
  def resetearValores
    ActiveRecord::Base.connection.execute("DELETE FROM gastos_envios")
    #ActiveRecord::Base.connection.execute("delete from sqlite_sequence where name = 'gastos_envios'")
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 0, :precio => 0
    GastosEnvio.create :id=>2, :tipo => "rango", :kilos => 0.01, :precio => 4
    GastosEnvio.create :id=>3, :tipo => "rango", :kilos => 5, :precio => 4
    GastosEnvio.create :id=>4, :tipo => "rango", :kilos => 10, :precio => 5
    GastosEnvio.create :id=>5, :tipo => "rango", :kilos => 20, :precio => 7
    GastosEnvio.create :id=>6, :tipo => "rango", :kilos => 30, :precio => 8
    GastosEnvio.create :id=>7, :tipo => "rango", :kilos => 40, :precio => 9
    GastosEnvio.create :id=>8, :tipo => "rango", :kilos => 50, :precio => 10
    GastosEnvio.create :id=>9, :tipo => "rango", :kilos => 60, :precio => 12
    GastosEnvio.create :id=>10, :tipo => "rango", :kilos => 70, :precio => 13
    GastosEnvio.create :id=>11, :tipo => "rango", :kilos => 80, :precio => 14
    GastosEnvio.create :id=>12, :tipo => "rango", :kilos => 90, :precio => 15
    GastosEnvio.create :id=>13, :tipo => "rango", :kilos => 100, :precio => 16
    GastosEnvio.create :id=>14, :tipo => "rango", :kilos => 110, :precio => 17
    GastosEnvio.create :id=>15, :tipo => "rango", :kilos => 120, :precio => 19
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 130, :precio => 20
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 140, :precio => 22
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 150, :precio => 23
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 160, :precio => 24
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 170, :precio => 25
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 180, :precio => 27
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 190, :precio => 28
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 200, :precio => 29
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 225, :precio => 30
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 250, :precio => 32
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 275, :precio => 33
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 300, :precio => 34
    GastosEnvio.create :id=>1, :tipo => "factorConversion", :kilos => -1, :precio => 225
    GastosEnvio.create :id=>1, :tipo => "gastosRembolso", :kilos => -1, :precio => 8
    redirect_to gastos_envios_path, notice: "Gastos de envio como al principio! OK"
  end
  def gastosEnvioCero
    ActiveRecord::Base.connection.execute("DELETE FROM gastos_envios")
    #ActiveRecord::Base.connection.execute("delete from sqlite_sequence where name = 'gastos_envios'")
    GastosEnvio.create :id=>1, :tipo => "rango", :kilos => 0, :precio => 0
    GastosEnvio.create :id=>1, :tipo => "factorConversion", :kilos => -1, :precio => 225
    GastosEnvio.create :id=>1, :tipo => "gastosRembolso", :kilos => -1, :precio => 8
    redirect_to gastos_envios_path, notice: "Sin gastos de envio. Solo tiene el reembolso! OK"
  end
end

app/helpers/gastos_envios_helper.rb
module GastosEnviosHelper
end

app/views/gastos_envios/_form.html.erb
<div class="row-fluid span12">
      <h1>Editar detalle de gastos de envio</h1>
    <%= form_for(@gastos_envio) do |f| %>
      <% if @gastos_envio.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@gastos_envio.errors.count, "Problema") %>. No ha podido ser salvado el cambio:</h2>

          <ul>
          <% @gastos_envio.errors.each do |attr, msg| %>
             <li><%= "#{msg}"%></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :id %>
        <%= f.text_field :id %> (Este es mejor no tocarlo. Se rellena solo)
      </div>

      <div class="hero-unit" style="/* IE10 Consumer Preview */ background-image: -ms-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Mozilla Firefox */ background-image: -moz-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Opera */ background-image: -o-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Webkit (Safari/Chrome 10) */ background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, #FFFFFF), color-stop(1, #FF871F)); /* Webkit (Chrome 11+) */ background-image: -webkit-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* W3C Markup, IE10 Release Preview */ background-image: linear-gradient(to top, #FFFFFF 0%, #FF871F 100%);">
        <div id="container-fluid">
          <section class="row-fluid" >
            <div class="span12">
              <div class="field span4">
                <%= f.label :tipo %>
                <%= f.text_field :tipo %>
              </div>
              <div class="field span4">
                <%= f.label :kilos %>
                <%= f.text_field :kilos %>
              </div>
              <div class="field span4">
                <%= f.label :precio %>
                <%= f.text_field :precio %>
              </div>
            </div>
          </section>
        </div>
      </div>
      <div class="actions">
        <%= f.submit "Aceptar cambios",class:"btn btn-success" %>
      </div>
    <% end %>
</div>
<%= link_to 'Volver a la lista de Gastos de envio', gastos_envios_path,class: "btn btn-link pull-right" %><i class="icon-backward pull-right"> </i>

app/views/gastos_envios/edit.html.erb
<%= render 'form' %>

app/views/gastos_envios/index.html.erb
<div class="span12">
  <div class="hero-unit" style="/* IE10 Consumer Preview */ background-image: -ms-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Mozilla Firefox */ background-image: -moz-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Opera */ background-image: -o-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* Webkit (Safari/Chrome 10) */ background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, #FFFFFF), color-stop(1, #FF871F)); /* Webkit (Chrome 11+) */ background-image: -webkit-linear-gradient(bottom, #FFFFFF 0%, #FF871F 100%); /* W3C Markup, IE10 Release Preview */ background-image: linear-gradient(to top, #FFFFFF 0%, #FF871F 100%);">
    <div id="container-fluid">
      <section class="row-fluid" >
        <div class="span12">
          <h3>Gestión de Gastos de Envio</h3>
          <%= link_to 'Volver al area de administración', admin_path, class: "btn btn-link pull-right" %><i class="icon-backward pull-right"> </i>
          <%= link_to 'Crear nueva regla', new_gastos_envio_path,class:"btn btn-link pull-right" %><i class="icon-plus pull-right"></i>
          <table class="table table-striped table-condensed ">
            <tr>
              <th style="background-color: #E67026;">Id.</th>
              <th style="background-color: #E67026;">Tipo</th>
              <th style="background-color: #E67026;">Kilos</th>
              <th style="background-color: #E67026;">Precio</th>
              <th style="background-color: #E67026;">Editar</th>
              <th style="background-color: #E67026;">Eliminar</th>
            </tr>
            <% @gastos_envios.each do |gastos_envio| %>
                <tr>
                  <td><%= gastos_envio.id %></td>
                  <td><%= gastos_envio.tipo %></td>
                  <td><%= gastos_envio.kilos %></td>
                  <td><%= gastos_envio.precio %></td>
                  <td><%= link_to 'Modificar', edit_gastos_envio_path(gastos_envio),class:"btn btn-success" %></td>
                  <td><%= link_to 'Borrar', gastos_envio, method: :delete, data: { confirm: '¿Estas seguro?' } ,class:"btn btn-danger" %></td>
                </tr>
            <% end %>
          </table>
          <br/>
        </div>
      </section>
    </div>
  </div>
</div>
<div class="row-fluid">

  <div class="span4"><%= link_to 'Crear nueva regla', new_gastos_envio_path,class:"btn btn-inverse" %></div>
  <div class="span4">
    <%= link_to 'Gastos de envio como al principio', "/gastos_envios/resetearValores",class:"btn btn-warning" %><br/><br/>
    <%= link_to 'Gastos de envio a 0, menos el reembolso', "/gastos_envios/gastosEnvioCero",class:"btn btn-warning" %> <br/>
  </div>
  <div class="span4"><i class="icon-backward"> </i><%= link_to 'Volver al area de administración', admin_path, class: "btn btn-link" %></div>
</div>

app/views/gastos_envios/new.html.erb
<%= render 'form' %>

app/views/gastos_envios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @gastos_envio.tipo %>
</p>

<p>
  <b>Kilos:</b>
  <%= @gastos_envio.kilos %>
</p>

<p>
  <b>Precio:</b>
  <%= @gastos_envio.precio %>
</p>


<%= link_to 'Edit', edit_gastos_envio_path(@gastos_envio) %> |
<%= link_to 'Back', gastos_envios_path %>