config/routes.rb
TiaAmparo::Application.routes.draw do

  get "tinymce_assets/create"

################disenyo_restauracion###############################
  get "disenyo/create"
  match 'disenyo' => 'disenyo#new', :as => 'disenyo', :via => :get
  match 'disenyo' => 'disenyo#create', :as => 'disenyo', :via => :post
################disenyo_restauracion#################

############zona verde######################
  resources :comments
  get "blog/index"
  match 'blog' => 'blog#new', :as => 'blog', :via => :get
  match 'blog' => 'blog#create', :as => 'blog', :via => :post
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :articles do
    collection do
      put :busqueda
    end
    resources :comments
  end
############zona verde###########################

############preguntas_frecuentes###########################
  get "preguntas_frecuentes/index"  ,as: 'preguntas_frecuentes'
############preguntas_frecuentes###########################

#########admin#########################
  get 'admin' => 'admin#index'
  get 'limpiezaBD' => 'admin#limpiezaBD'
#########admin##########################

#########usuarios#########################
  resources :password_resets
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources  :users do
    collection do
      get :areaUsuario
      put :busqueda
    end
  end
##########usuarios########################

##########tienda########################
  resources :gastos_envios do
    collection do
      get :resetearValores
      get :gastosEnvioCero
    end
  end
  resources  :line_items,:carts
  match 'store' => 'store#index', :as => 'store', :via => :get
  get "/store/index"
  get "/store/ceramica"
  get "/store/pintura"
  get "/store/jabones_naturales"
  get "/store/serijos"
  get "/store/bisuteria"
  get "/store/decoracion"
  get "/store/antiguedades"
  get "/store/muebles"
  get "/store/vinos"
  get "/store/quesos"
  get "/store/souvenires"
  get "/store/varios"
  put "/store/busqueda"

  resources :products do
    collection do
      put :busqueda
    end
  end

  resources :orders do
    collection do
      put :busqueda
    end
  end
##########tienda########################

############galeria_fotos######################
  resources :galeria_fotos do
    collection do
      get :verGaleriaFotos
      put :busqueda
    end
  end
############galeria_fotos#####################

############contacto#####################
  get "contacto/create"
  match 'contacto' => 'contacto#new', :as => 'contacto', :via => :get
  match 'contacto' => 'contacto#create', :as => 'contacto', :via => :post
############contacto#####################

############inicio#####################
  get "inicio/index"
  root to: 'inicio#index' , as: 'inicio'
############inicio#####################
end

app/views/admin/index.html.erb
<% #encoding: utf-8 %>
<div class="hero-unit">
  <div class="row-fluid show-grid">
    <div class="span3">
      <div class="hero-unit">
        <h3 align="center"><u>Tienda</u></h3>
        <ul>
          <li><%= link_to 'Pedidos', orders_path, class:"btn btn-link" %></li>
          <li><%= link_to 'Productos', products_path, class:"btn btn-link" %></li>
          <li><%= link_to 'Gestión gastos envio', gastos_envios_path, class:"btn btn-link" %></li>
        </ul>
        <i class="icon-plus"></i><%= link_to ' Nuevo producto', new_product_path, class:"btn btn-link" %></i>
      </div>
    </div>
    <div class="span3">
      <div class="hero-unit">
        <h3 align="center"><u>Blog</u></h3>
        <ul>
          <li><%= link_to 'Artículos y comentarios', articles_path, class:"btn btn-link" %></li>
        </ul>
        <i class="icon-plus"></i><%= link_to ' Nueva entrada', new_article_path, class:"btn btn-link" %>
      </div>
    </div>

    <div class="span3">
      <div class="hero-unit">
        <h3 align="center"><u>Usuarios</u></h3>
        <ul>
            <li><%= link_to 'Usuarios', users_path, class:"btn btn-link" %></li>
        </ul>
      </div>
    </div>
    <div class="span3">
      <div class="hero-unit">
        <h3 align="center"><u>Diseño&Restaura.</u></h3>
        <ul>
          <li><%= link_to 'Imágenes de la galeria', galeria_fotos_path, class:"btn btn-link" %></li>
        </ul>
        <i class="icon-plus"></i><%= link_to 'Nueva imagen a galeria', new_galeria_foto_path, class:"btn btn-link" %>
      </div>
    </div>
  </div>
  <div class="row-fluid" >
    <div class="span3" style="padding-left: 20px">
      Versión del programa
      <!-- Button to trigger modal -->
      <a href="#myModa" role="button" class="btn btn-link" data-toggle="modal">1.0</a>
      <!-- Modal -->
      <div id="myModa" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Detalles de las versiones </h3>
        </div>
        <div class="modal-body">
          <!-- Escribir aquí nuevas revisiones-->
         <h3>Versión 1.0</h3>
          Comienzo del proyecto<br/>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
      </div>
    </div>
    <div class="span8 pull-right" style="padding-right: 20px">
      <i class="icon-hand-left pull-right"></i><%= link_to 'Limpiar base de datos (ya lo has hecho al entrar como admin :P )', limpiezaBD_path, class:"btn btn-link pull-right" %><i class="icon-hand-right pull-right"></i>
    </div>
  </div>
</div>

<%= button_to 'Salir de la sesión de Administracion', logout_path, method: :delete,class:"btn btn-large btn-danger", style: "font-size: 20px;" %>