config/routes.rb
TiaAmparo::Application.routes.draw do

  get "tinymce_assets/create"

################disenyo_restauracion###############################
  get "disenyo/create"
  match 'disenyo' => 'disenyo#new', :as => 'disenyo', :via => :get
  match 'disenyo' => 'disenyo#create', :as => 'disenyo', :via => :post
################disenyo_restauracion#################

############zona verde######################
  resources :comments
  get "blog/index"
  match 'blog' => 'blog#new', :as => 'blog', :via => :get
  match 'blog' => 'blog#create', :as => 'blog', :via => :post
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :articles do
    collection do
      put :busqueda
    end
    resources :comments
  end
############zona verde###########################

############preguntas_frecuentes###########################
  get "preguntas_frecuentes/index"  ,as: 'preguntas_frecuentes'
############preguntas_frecuentes###########################

#########admin#########################
  get 'admin' => 'admin#index'
  get 'limpiezaBD' => 'admin#limpiezaBD'
#########admin##########################

#########usuarios#########################
  resources :password_resets
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources  :users do
    collection do
      get :areaUsuario
      put :busqueda
    end
  end
##########usuarios########################

##########tienda########################
  resources :gastos_envios do
    collection do
      get :resetearValores
      get :gastosEnvioCero
    end
  end
  resources  :line_items,:carts
  match 'store' => 'store#index', :as => 'store', :via => :get
  get "/store/index"
  get "/store/ceramica"
  get "/store/pintura"
  get "/store/jabones_naturales"
  get "/store/serijos"
  get "/store/bisuteria"
  get "/store/decoracion"
  get "/store/antiguedades"
  get "/store/muebles"
  get "/store/vinos"
  get "/store/quesos"
  get "/store/souvenires"
  get "/store/varios"
  put "/store/busqueda"

  resources :products do
    collection do
      put :busqueda
    end
  end

  resources :orders do
    collection do
      put :busqueda
    end
  end
##########tienda########################

############galeria_fotos######################
  resources :galeria_fotos do
    collection do
      get :verGaleriaFotos
      put :busqueda
    end
  end
############galeria_fotos#####################

############contacto#####################
  get "contacto/create"
  match 'contacto' => 'contacto#new', :as => 'contacto', :via => :get
  match 'contacto' => 'contacto#create', :as => 'contacto', :via => :post
############contacto#####################

############inicio#####################
  get "inicio/index"
  root to: 'inicio#index' , as: 'inicio'
############inicio#####################
end

app/models/cart.rb
#encoding: utf-8
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  #has_many :line_items-> un carro tendra varios line items
  #dependent: :destroy->  si borramos un carro, se eliminaran toda tupla de
  #                       line_items asociada a ese carro. La asociacion esta
  #                       en el modelo line_items.rb
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def cantidadItems
    line_items.to_a.sum { |item| item.total_elements }
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
  def total_volumen
    line_items.to_a.sum { |item| item.total_volumen }
  end
  def calculoGastosEnvio
    $pesoTotal=total_volumen
    $factorConversion=GastosEnvio.select(:precio).where('tipo LIKE "factorConversion"').first#255 #225 kg. /m3

    $volumenKG=$pesoTotal*$factorConversion.precio

    $busquedaPrecioRango=GastosEnvio.select(:precio).where("tipo LIKE 'rango' AND kilos>=#{$volumenKG}").order("precio ASC").first#255 #225 kg. /m3
    if ($busquedaPrecioRango==nil)
      $maximoPeso=GastosEnvio.maximum("kilos")
      $busquedaPrecioRango=GastosEnvio.select(:precio).where("tipo LIKE 'rango' AND kilos=#{$maximoPeso}").order("precio ASC").first#255 #225 kg. /m3
    end

    return $busquedaPrecioRango.precio
=begin
    if $volumenKG==0
      return 0
    elsif $volumenKG>0 && $volumenKG<=5
      return 4
    elsif $volumenKG>5 && $volumenKG<=10
      return 5
    elsif $volumenKG>10 && $volumenKG<=20
      return 7
    elsif $volumenKG>20 && $volumenKG<=30
      return 8
    elsif $volumenKG>30 && $volumenKG<=40
      return 9
    elsif $volumenKG>40 && $volumenKG<=50
      return 10
    elsif $volumenKG>50 && $volumenKG<=60
      return 12
    elsif $volumenKG>60 && $volumenKG<=70
      return 13
    elsif $volumenKG>70 && $volumenKG<=80
      return 14
    elsif $volumenKG>80 && $volumenKG<=90
      return 15
    elsif $volumenKG>90 && $volumenKG<=100
      return 16
    elsif $volumenKG>100 && $volumenKG<=110
      return 17
    elsif $volumenKG>110 && $volumenKG<=120
      return 19
    elsif $volumenKG>120 && $volumenKG<=130
      return 20
    elsif $volumenKG>130 && $volumenKG<=140
      return 22
    elsif $volumenKG>140 && $volumenKG<=150
      return 23
    elsif $volumenKG>150 && $volumenKG<=160
      return 24
    elsif $volumenKG>160 && $volumenKG<=170
      return 25
    elsif $volumenKG>170 && $volumenKG<=180
      return 27
    elsif $volumenKG>180 && $volumenKG<=190
      return 28
    elsif $volumenKG>190 && $volumenKG<=200
      return 29
    elsif $volumenKG>200 && $volumenKG<=225
      return 30
    elsif $volumenKG>225 && $volumenKG<=250
      return 32
    elsif $volumenKG>250 && $volumenKG<=275
      return 33
    elsif $volumenKG>275 && $volumenKG<=300
      return 34
    elsif $volumenKG>300
      return 35
    end
=end
  end
  def totalAPagar
    calculoGastosEnvio+total_price
  end
  def gastosReembolso
    $busquedaGastosReembolso=GastosEnvio.select(:precio).where('tipo LIKE "gastosRembolso"').first
    Rails.logger.error  "-------------------busquedaPrecioRango: "+$busquedaGastosReembolso.precio.to_s
    return $busquedaGastosReembolso.precio #expresado en €
  end

end

app/controllers/carts_controller.rb
#encoding: utf-8
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  skip_before_filter :filtro_admin
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
      else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])
    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url,
      notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<table class="table table-condensed" style="border-top: 0px">
  <%= render(cart.line_items) %>
  <tr class="total_line">
  <tr><td style="border-top: 0px solid #000000"></td></tr>
  <tr><td style="border-top: 0px solid #000000"></td></tr>
    <td colspan="2" style="border-top: 5px solid #000000">Total del pedido</td>
    <td class="total_cell" style="border-top: 5px solid #000000"><%= number_to_currency(cart.total_price,:unit=>'€',format: "%n %u") %></td>
  </tr>
    <td colspan="2">Gastos Envio</td>
    <td class="total_cell"> <%= number_to_currency(cart.calculoGastosEnvio,:unit=>'€',format: "%n %u")%></td>
  <tr>
  </tr>

  <td colspan="2">Total a Pagar</td>
  <td class="total_cell"> <b><%= number_to_currency(cart.totalAPagar,:unit=>'€',format: "%n %u")%></b></td>
  <tr>
  </tr>

</table>

<% if cart.total_price>0%>
<%= button_to 'Cancelar compra', cart, method: :delete, class:"btn btn-warning",
    data: { confirm: 'Are you sure?' } %>
<%= button_to "Encargar pedido", new_order_path, method: :get, class:"btn btn-primary",id:"btnEncargar"%>
<%end%>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<table>
  <%= render(@cart.line_items) %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>
<%= button_to 'Empty cart', @cart, method: :delete,
    data: { confirm: 'Are you sure?' } %>